exec(open(r'f:\mission-git-hackss\mission-git-hackss\ext4parse.py').read().split('parse_dir(2')[0])
raw=read_inode(32)
size=inode_size_bytes(raw)
flags=u32(raw,32)
print('size',size,'flags',hex(flags),'extents?',bool(flags&0x80000))
data=read_file(32)
print('len',len(data))
print('--- raw hex ---')
print(data.hex())
print('--- ascii ---')
print(''.join(chr(c) if 32<=c<127 else '.' for c in data))
open(r'f:\mission-git-hackss\mission-git-hackss\deleted_ino32.bin','wb').write(data)
