"""Automatic writeup generation"""

from datetime import datetime
from pathlib import Path
from typing import List, Optional
import json

from core.challenge import Challenge, ChallengeResult


class WriteupGenerator:
    """Generate writeups for solved challenges"""
    
    def __init__(self, output_dir: str = 'writeups'):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def generate(self, result: ChallengeResult, format: str = 'markdown') -> str:
        """Generate writeup for challenge result"""
        if format == 'markdown':
            return self._generate_markdown(result)
        elif format == 'html':
            return self._generate_html(result)
        elif format == 'json':
            return self._generate_json(result)
        else:
            return self._generate_markdown(result)
    
    def _generate_markdown(self, result: ChallengeResult) -> str:
        """Generate Markdown writeup"""
        challenge = result.challenge
        
        writeup = f"""# {challenge.name}

## Challenge Information

- **Category**: {challenge.category or 'Unknown'}
- **Points**: {challenge.points}
- **Solved**: {'✅ Yes' if result.success else '❌ No'}
- **Flag**: `{result.flag or 'N/A'}`
- **Method**: {result.method or 'N/A'}
- **Duration**: {result.duration:.2f} seconds
- **Timestamp**: {result.timestamp.strftime('%Y-%m-%d %H:%M:%S')}

## Description

{challenge.description or 'No description provided.'}

## Solution

### Approach

The challenge was solved using the **{result.method or 'automated'}** technique.

### Steps

"""
        # Add logs as steps
        for i, log in enumerate(result.logs, 1):
            writeup += f"{i}. {log}\n"
        
        writeup += f"""
### Flag

```
{result.flag or 'Flag not found'}
```

## Lessons Learned

- Category: {challenge.category}
- Technique: {result.method}
- Time to solve: {result.duration:.2f}s

---

*Generated by MD-EXPLOIT-ENGINE on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return writeup
    
    def _generate_html(self, result: ChallengeResult) -> str:
        """Generate HTML writeup"""
        challenge = result.challenge
        
        logs_html = '\n'.join(f'<li>{log}</li>' for log in result.logs)
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{challenge.name} - Writeup</title>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #333; }}
        .info {{ background: #f5f5f5; padding: 15px; border-radius: 5px; }}
        .flag {{ background: #d4edda; padding: 10px; border-radius: 5px; font-family: monospace; }}
        .success {{ color: #28a745; }}
        .failed {{ color: #dc3545; }}
        code {{ background: #f0f0f0; padding: 2px 5px; border-radius: 3px; }}
    </style>
</head>
<body>
    <h1>{challenge.name}</h1>
    
    <div class="info">
        <p><strong>Category:</strong> {challenge.category or 'Unknown'}</p>
        <p><strong>Points:</strong> {challenge.points}</p>
        <p><strong>Status:</strong> <span class="{'success' if result.success else 'failed'}">
            {'Solved' if result.success else 'Not Solved'}</span></p>
        <p><strong>Method:</strong> {result.method or 'N/A'}</p>
        <p><strong>Duration:</strong> {result.duration:.2f}s</p>
    </div>
    
    <h2>Description</h2>
    <p>{challenge.description or 'No description provided.'}</p>
    
    <h2>Solution Steps</h2>
    <ol>{logs_html}</ol>
    
    <h2>Flag</h2>
    <div class="flag">{result.flag or 'Flag not found'}</div>
    
    <hr>
    <p><em>Generated by MD-EXPLOIT-ENGINE on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>
</body>
</html>"""
    
    def _generate_json(self, result: ChallengeResult) -> str:
        """Generate JSON writeup"""
        return json.dumps(result.to_dict(), indent=2, default=str)
    
    def save(self, result: ChallengeResult, format: str = 'markdown') -> Path:
        """Save writeup to file"""
        content = self.generate(result, format)
        
        ext = {'markdown': 'md', 'html': 'html', 'json': 'json'}.get(format, 'md')
        filename = f"{result.challenge.name}_{result.timestamp.strftime('%Y%m%d_%H%M%S')}.{ext}"
        filepath = self.output_dir / filename
        
        filepath.write_text(content)
        return filepath
    
    def generate_summary(self, results: List[ChallengeResult]) -> str:
        """Generate summary of multiple challenges"""
        solved = [r for r in results if r.success]
        failed = [r for r in results if not r.success]
        
        total_time = sum(r.duration for r in results)
        
        summary = f"""# CTF Summary

## Statistics

- **Total Challenges**: {len(results)}
- **Solved**: {len(solved)}
- **Failed**: {len(failed)}
- **Success Rate**: {len(solved)/len(results)*100:.1f}%
- **Total Time**: {total_time:.2f}s

## Solved Challenges

| Challenge | Category | Flag | Method | Time |
|-----------|----------|------|--------|------|
"""
        for r in solved:
            summary += f"| {r.challenge.name} | {r.challenge.category} | `{r.flag[:20]}...` | {r.method} | {r.duration:.2f}s |\n"
        
        summary += f"""
## Failed Challenges

| Challenge | Category | Error |
|-----------|----------|-------|
"""
        for r in failed:
            summary += f"| {r.challenge.name} | {r.challenge.category} | {r.error} |\n"
        
        summary += f"""
---

*Generated by MD-EXPLOIT-ENGINE on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return summary
